// Code generated by ent, DO NOT EDIT.

package ent

import (
	"testserver/ent/schema"
	"testserver/ent/task"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[0].Descriptor()
	// task.DefaultTitle holds the default value on creation for the title field.
	task.DefaultTitle = taskDescTitle.Default.(string)
	// taskDescContent is the schema descriptor for content field.
	taskDescContent := taskFields[1].Descriptor()
	// task.DefaultContent holds the default value on creation for the content field.
	task.DefaultContent = taskDescContent.Default.(string)
}
